import Header from "../components/header/header";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Post - Hanko Image Gallery",
  description: "Generated by create next app",
};

export default function PostLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="bg-[#262B35]">
      <header className="bg-[#262B35] sticky top-0 pt-3">
        <Header />
      </header>
      <div>{children}</div>
    </body>
  );
}