import Header from "../components/header/header";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard - Hanko Image Gallery",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="bg-[#262B35] sticky top-0 z-10 pt-3">
        <Header />
      </div>
      <div>{children}</div>
    </main>
  );
}
